- .travis.yml
- README.md
- app/waf/package.json
- app/waf/test/acceptance/unkown.path.acceptance.ts
- app/waf/test/unit/application.unit.ts
Coverage report is placed at https://coveralls.io/github/F5Networks/f5-adcaas-openstack
> Test coverage report

- app/waf/package.json
- app/waf/src/controllers/ping.controller.ts
- app/waf/src/datasources/as3.datasource.json
- app/waf/src/datasources/as3.datasource.ts
- app/waf/src/datasources/index.ts
- app/waf/src/services/as3.service.ts
- app/waf/src/services/index.ts
- app/waf/test/acceptance/ping.controller.acceptance.ts
This code change only add AS3 info service. Other services will be added later. Since LB4 currently does not support to stub service object. We will defer the unit test of AS3 service code.
> Define AS3 info service

- app/waf/src/datasources/db.datasource.ts
This is the patch to fix CI error in master branch.
> Make some datasource parameter to be optional

- app/waf/src/controllers/adc.controller.ts
- app/waf/src/controllers/index.ts
- app/waf/src/models/adc.model.ts
- app/waf/src/models/index.ts
- app/waf/src/repositories/adc.repository.ts
- app/waf/src/repositories/index.ts
- app/waf/test/acceptance/adc.controller.acceptance.ts
- app/waf/test/helpers/database.helpers.ts
Add Adc model and related logic/acceptance test. 
Next: make uuid to be automated generated.
> Add ADC model/repository/controller

- app/waf/src/controllers/index.ts
- app/waf/src/controllers/pool.controller.ts
- app/waf/src/controllers/service.controller.ts
- app/waf/src/models/index.ts
- app/waf/src/models/pool.model.ts
- app/waf/src/models/service.model.ts
- app/waf/src/repositories/index.ts
- app/waf/src/repositories/pool.repository.ts
- app/waf/src/repositories/service.repository.ts
- app/waf/test/acceptance/pool.contoller.acceptance.ts
- app/waf/test/acceptance/service.controller.acceptance.ts
- app/waf/test/helpers/database.helpers.ts
> Add pool model and its tests (code change based on service model)

- app/waf/.gitignore
- app/waf/.vscode/launch.json
- app/waf/.vscode/tasks.json
- app/waf/package.json
- app/waf/tsconfig.json
Make it possible to debug the repo via step-by-step mode.
> Enable debug for developing.

- scripts/publish_api_ref.sh
Fix "/bin/bash: - : invalid option"
> Fix api doc deploy script

- app/waf/src/controllers/application.controller.ts
- app/waf/src/controllers/rule.controller.ts
- app/waf/src/models/action.model.ts
- app/waf/src/models/application.model.ts
- app/waf/src/models/as3.model.ts
- app/waf/src/models/condition.model.ts
- app/waf/src/models/index.ts
- app/waf/src/models/pool.model.ts
- app/waf/src/models/rule.model.ts
- app/waf/src/repositories/action.repository.ts
- app/waf/src/repositories/condition.repository.ts
- app/waf/src/repositories/index.ts
- app/waf/src/repositories/rule.repository.ts
- app/waf/test/acceptance/action.controller.acceptance.ts
- app/waf/test/acceptance/application.controller.acceptance.ts
- app/waf/test/acceptance/condition.controller.acceptance.ts
- app/waf/test/helpers/database.helpers.ts
code change for rule -> conditions/actions
> Rule hasMany Conditions and Actions

- app/waf/src/controllers/rule.controller.ts
- app/waf/src/models/action.model.ts
- app/waf/src/models/condition.model.ts
- app/waf/test/acceptance/action.controller.acceptance.ts
- app/waf/test/acceptance/condition.controller.acceptance.ts
- app/waf/test/acceptance/rule.controller.acceptance.ts
conform to the naming conversion and reuse the commonEntity base class
> conform to the naming conversion and reuse the commonEntity base class

- app/waf/src/models/as3.model.ts
Do we really need to declare kinds of AS3 classes for that?
> add todo item.

- app/waf/src/controllers/adc.controller.ts
- app/waf/src/controllers/application.controller.ts
> A workaround for globalThis issue

- app/waf/src/datasources/openstack.datasource.json
- app/waf/src/services/identity.service.ts
- app/waf/test/acceptance/openstack.controller.acceptance.ts
- app/waf/test/fixtures/controllers/mocks/mock.openstack.controller.ts
- app/waf/test/fixtures/controllers/openstack.controller.ts
So that it can be easy to bebug/issue-locate.
> Move the identity definition of json body to services*.ts

- app/waf/src/controllers/monitor.controller.ts
- app/waf/src/controllers/pool.controller.ts
- app/waf/src/models/member.model.ts
- app/waf/src/models/monitor.model.ts
- app/waf/src/models/pool.model.ts
- app/waf/src/repositories/member.repository.ts
- app/waf/src/repositories/monitor.repository.ts
- app/waf/src/repositories/pool.repository.ts
- app/waf/test/acceptance/application.controller.acceptance.ts
- app/waf/test/acceptance/member.controller.acceptance.ts
- app/waf/test/acceptance/monitor.controller.acceptance.ts
- app/waf/test/acceptance/pool.contoller.acceptance.ts
- app/waf/test/helpers/database.helpers.ts
Pool, Monitor, and member will delivery as 3 commits in one PR.
> Revision pool, member, monitor APIs

- app/waf/src/controllers/endpointpolicy.controller.ts
- app/waf/src/controllers/rule.controller.ts
- app/waf/src/models/action.model.ts
- app/waf/src/models/as3.model.ts
- app/waf/src/models/condition.model.ts
- app/waf/src/models/endpointpolicy.model.ts
- app/waf/src/models/rule.model.ts
- app/waf/src/repositories/action.repository.ts
- app/waf/src/repositories/condition.repository.ts
- app/waf/src/repositories/endpointpolicy.repository.ts
- app/waf/src/repositories/rule.repository.ts
- app/waf/test/acceptance/action.controller.acceptance.ts
- app/waf/test/acceptance/condition.controller.acceptance.ts
- app/waf/test/acceptance/endpointpolicy.controller.acceptance.ts
- app/waf/test/acceptance/rule.controller.acceptance.ts
- app/waf/test/helpers/database.helpers.ts
Refactor APIs of endpointpolicy/rule/condition/action
> Refactor the action/condition/rule/endpointpolicy

- app/waf/src/models/action.model.ts
- app/waf/src/models/condition.model.ts
- app/waf/src/models/endpointpolicy.model.ts
- app/waf/src/models/rule.model.ts
- app/waf/test/acceptance/rule.controller.acceptance.ts
- app/waf/test/helpers/database.helpers.ts
- ！
modify based on the review suggestions
> modify based on the review suggestions

- app/waf/src/datasources/openstack.datasource.json
- app/waf/src/sequence.ts
- app/waf/src/services/compute.service.ts
- app/waf/src/services/identity.service.ts
- app/waf/src/services/network.service.ts
- app/waf/test/acceptance/openstack.controller.acceptance.ts
- app/waf/test/fixtures/controllers/mocks/mock.openstack.controller.ts
- app/waf/test/fixtures/controllers/openstack.controller.ts
related operations include: 
1. admin token generation/parsing. 
2. URL assembling. 
3. compatible between v2.0 and v3.
> Collect auth token related operations into AuthedToken class.

- deploy/README.md
For (internal) sync up of the testing environment setup.
> Add a brief introduction to dev, test, prod process.

- app/waf/index.js
- deploy/appcluster.rc
change some test env variables
> change some env varibles

- app/waf/.gitignore
- app/waf/src/controllers/base.controller.ts
- app/waf/src/controllers/membermonitorassc.controller.ts
- app/waf/src/controllers/monitor.controller.ts
- app/waf/src/controllers/pool.controller.ts
- app/waf/src/repositories/common.ts
- app/waf/test/acceptance/member.controller.acceptance.ts
- app/waf/test/acceptance/membermonitorassoc.controller.acceptance.ts
- app/waf/test/acceptance/monitor.controller.acceptance.ts
- app/waf/test/acceptance/pool.contoller.acceptance.ts
- app/waf/test/helpers/database.helpers.ts
This RP contains `one to many`, `many to many` example.
> add base controller to move tenantId

- app/waf/src/controllers/poolmonitorassc.controller.ts
- app/waf/test/acceptance/poolmonitorassoc.controller.acceptance.ts
many to many relationships. (it is the same with add multi-tenancy for membermonitorassc `commit 4295f089dbefafba3152192a15bd2bc536038bdb`)
> add mutltitenancy to poolmonitorassoc

- app/waf/src/controllers/service.controller.ts
- app/waf/test/acceptance/endpointpolicyassoc.controller.acceptance.ts
- app/waf/test/acceptance/service.controller.acceptance.ts
- app/waf/test/helpers/database.helpers.ts
> add mutltitenancy to service

- app/waf/src/controllers/monitor.controller.ts
- app/waf/src/controllers/pool.controller.ts
- app/waf/src/controllers/service.controller.ts
- app/waf/src/models/common.model.ts
add tenantId at creating for monitor, pool, member, service at once.
> add tenantId at create for monitor, pool, member, service

- app/waf/src/controllers/rule.controller.ts
- app/waf/test/acceptance/action.controller.acceptance.ts
- app/waf/test/acceptance/condition.controller.acceptance.ts
- app/waf/test/acceptance/rule.controller.acceptance.ts
- app/waf/test/helpers/database.helpers.ts
multiple tenant resource polish
> rule/condition/action multiple-tenant enhancement

- app/waf/src/controllers/adc.controller.ts
(cherry picked from commit 6d85aa35acbed0ee26701f14534ba455832cdb2f)
> Remove the lastErr when next state comes.

- deploy/appcluster.rc
In .vscode/launch.json, we may also need to update the environment variable: 
//"DO_ENDPOINT": "http://localhost:8081",
"DO_ENDPOINT": "https://localhost:9443",
FYI. @haoshen61 @zhang-shengping @jikui @Niklaus-xie
> Need to update DO endpoint after we use DO 1.5.0

- app/waf/src/controllers/adc.controller.ts
Simply remove the multiple line log.
> Remove the multiple-line log output.

- app/waf/test/acceptance/adc.controller.acceptance.ts
TypeError: test_helper_1.setupEnvs(...).then(...).finally is not a function
It's strange that, local `npm test` desn't show this error.
> Fix the issue caused by promise.then.finally.

- app/waf/src/controllers/endpointpolicy.controller.ts
- app/waf/src/controllers/pool.controller.ts
- app/waf/src/controllers/rule.controller.ts
- app/waf/test/acceptance/action.controller.acceptance.ts
- app/waf/test/acceptance/condition.controller.acceptance.ts
- app/waf/test/acceptance/member.controller.acceptance.ts
- app/waf/test/acceptance/rule.controller.acceptance.ts
Original code returns a wrong list.
> fix one-to-many issue and test it

- app/waf/src/services/do.service.ts
- deploy/appcluster.rc
parameterize  the ve configuration items
> paramaterize the ve configuration items

- app/waf/src/controllers/adc.controller.ts
- app/waf/src/models/adc.model.ts
- app/waf/test/acceptance/adc.controller.acceptance.ts
> Setup action API into URL Path

- app/waf/src/controllers/adc.controller.ts
- app/waf/src/controllers/declaration.controller.ts
- app/waf/src/repositories/action.repository.ts
- app/waf/src/repositories/adc.repository.ts
- app/waf/src/repositories/application.repository.ts
- app/waf/src/repositories/common.ts
- app/waf/src/repositories/condition.repository.ts
- app/waf/src/repositories/declaration.repository.ts
- app/waf/src/repositories/endpointpolicy.repository.ts
- app/waf/src/repositories/member.repository.ts
- app/waf/src/repositories/monitor.repository.ts
- app/waf/src/repositories/pool.repository.ts
- app/waf/src/repositories/rule.repository.ts
- app/waf/src/repositories/service.repository.ts
- app/waf/src/repositories/wafpolicy.repository.ts
- app/waf/src/sequence.ts
- app/waf/src/services/asg.service.ts
- app/waf/src/services/bigip.service.ts
- app/waf/src/services/compute.service.ts
- app/waf/src/services/do.service.ts
- app/waf/src/services/network.service.ts
> add requestId in logger names

- deploy/docker-compose.yml
- deploy/docker/fluent/Dockerfile
- deploy/fluentd.conf
- deploy/kibana.yml
> Spike: add EFK for adcaas (this code will not merge to master, unless future it is required)

- app/waf/src/controllers/application.controller.ts
- app/waf/src/controllers/monitor.controller.ts
- app/waf/src/models/action.model.ts
- app/waf/src/models/application.model.ts
- app/waf/test/acceptance/application.controller.acceptance.ts
Application Validation and  Test
> Application Validation

- app/waf/test/acceptance/action.controller.acceptance.ts
- app/waf/test/acceptance/adc.controller.acceptance.ts
- app/waf/test/acceptance/application.controller.acceptance.ts
- app/waf/test/acceptance/condition.controller.acceptance.ts
- app/waf/test/acceptance/declaration.controller.acceptance.ts
- app/waf/test/acceptance/endpointpolicy.controller.acceptance.ts
- app/waf/test/acceptance/endpointpolicyassoc.controller.acceptance.ts
- app/waf/test/acceptance/home-page.acceptance.ts
- app/waf/test/acceptance/member.controller.acceptance.ts
- app/waf/test/acceptance/membermonitorassoc.controller.acceptance.ts
- app/waf/test/acceptance/mock.selftest.controller.acceptance.ts
- app/waf/test/acceptance/monitor.controller.acceptance.ts
- app/waf/test/acceptance/openstack.controller.acceptance.ts
- app/waf/test/acceptance/ping.controller.acceptance.ts
- app/waf/test/acceptance/pool.contoller.acceptance.ts
- app/waf/test/acceptance/poolmonitorassoc.controller.acceptance.ts
- app/waf/test/acceptance/rule.controller.acceptance.ts
- app/waf/test/acceptance/sequence.acceptance.ts
- app/waf/test/acceptance/service.controller.acceptance.ts
- app/waf/test/acceptance/tenantassoc.controller.acceptance.ts
- app/waf/test/acceptance/unkown.path.acceptance.ts
- app/waf/test/acceptance/wafpolicy.controller.acceptance.ts
- app/waf/test/fixtures/controllers/mocks/mock.asg.controller.ts
- app/waf/test/fixtures/controllers/mocks/mock.bigip.controller.ts
- app/waf/test/fixtures/controllers/mocks/mock.do.controller.ts
- app/waf/test/fixtures/controllers/mocks/mock.openstack.controller.ts
- app/waf/test/fixtures/datasources/testrest.datasource.ts
- app/waf/test/helpers/database.helpers.ts
- app/waf/test/helpers/testsetup-helper.ts
- app/waf/test/unit/AdcStateCtrlr.unit.ts
To make it easier to write/maintain.
> Refactor acceptance test framework. 

- scripts/publish_api_ref.sh
Need to wait for a little more seconds...
> Fix deploy job

- app/waf/some-prerequisites.md
> doc only to review

- test/os-queens-environment.json
Change image name to BIGIP-13.1.1
> Change image name to BIGIP-13.1.1

- app/portal/Dockerfile
- app/portal/horizon/openstack_dashboard/api/f5wafaas.py
- app/portal/horizon/openstack_dashboard/dashboards/f5services/static/dashboard/f5services/workflow/launch-instance/launch-instance-model.service.js
- app/portal/horizon/openstack_dashboard/local/.gitignore
- app/portal/horizon/openstack_dashboard/local/.secret_key_store
- app/portal/horizon/openstack_dashboard/local/local_settings.py
- app/portal/scripts/venv.rc
- app/waf/index.js
- scripts/generate_certs.sh
- scripts/start_all.sh
1. processs -> process in app/waf/index.js
2. update SESSION_ENGINE to fix login issue.
3. fix .svg display issue in docker
4. rename WAFAAS_URL to ADCAAS_ENDPOINT.
> Fix several issues of portal.

- app/waf/test/unit/utils.runWithTimer.ts
AssertionError: expected 100 to be above 100
> Fix the travis issue caused by runWithTimer.

- app/waf/test/unit/utils.runWithTimer.ts
- deploy/appcluster.rc
- scripts/download_as3.sh
Including kinds of "Added support for ..." and bugfixes.
> Update AS3 version from 3.10.0-5 to 3.14.0-4.

- app/waf/src/controllers/cert.controller.ts
- app/waf/src/controllers/index.ts
- app/waf/src/controllers/key.controller.ts
- app/waf/src/datasources/asg.datasource.json
- app/waf/src/datasources/bigip.datasource.json
- app/waf/src/models/cert.model.ts
- app/waf/src/models/index.ts
- app/waf/src/models/key.model.ts
- app/waf/src/repositories/cert.repository.ts
- app/waf/src/repositories/index.ts
- app/waf/src/repositories/key.repository.ts
- app/waf/src/services/asg.service.ts
- app/waf/src/services/bigip.service.ts
- app/waf/test/acceptance/cert.controller.acceptance.ts
- app/waf/test/acceptance/key.controller.acceptance.ts
- app/waf/test/helpers/database.helpers.ts
upload and install keys and certs.
> upload install keys and certs.

- app/portal/horizon/requirements.txt
https://github.com/F5Networks/f5-adcaas-openstack/security/dependabot/app/portal/horizon/requirements.txt/django/open
> fix Incorrect Default Permissions(CVE-2020-24583)
